import json
import datetime
import gradio as gr
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load model and tokenizer
model_name = "google/flan-t5-large"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# JSONL file to store GAIA submissions
GAIA_FILE = "gaia_submission.jsonl"

def run_agent(task_text):
    # Generate answer
    inputs = tokenizer(task_text, return_tensors="pt")
    outputs = model.generate(**inputs, max_length=200)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Prepare GAIA JSONL entry
    task_id = f"task_{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}"
    entry = {
        "task_id": task_id,
        "model_answer": answer,
        "reasoning_trace": f"Generated by Flan-T5 for input: {task_text}"
    }

    # Append entry to JSONL file
    with open(GAIA_FILE, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")

    return answer

# Gradio interface
demo = gr.Interface(
    fn=run_agent,
    inputs="text",
    outputs="text",
    title="GAIA Agent",
    description="Ask questions to the Flan-T5 GAIA agent! Answers are saved automatically."
)

# Launch app
demo.launch(share=True)
